"use client";
// Future: replace jsPDF with server-side Puppeteer for better fidelity
import { Supplier, Seeker, DocTemplate } from "./types";

function addWrappedText(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  doc: any,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

const DISCLAIMER =
  "DISCLAIMER: This document is generated by a guidance tool for informational purposes only. All data, pricing, contacts, and legal terms must be independently verified by qualified legal counsel and licensed engineers. This does not constitute legal, financial, or engineering advice. PowerMatch Advisors earns a success-based brokerage fee per executed transaction.";

export async function generatePDF(
  template: DocTemplate,
  supplier: Supplier | null,
  seeker: Seeker | null
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });

  const margin = 20;
  const pageW = 215.9;
  const contentW = pageW - margin * 2;
  const lineH = 6;
  let y = margin;

  const h1 = (text: string) => {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, y);
    y += 10;
  };
  const h2 = (text: string) => {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, y);
    y += 8;
  };
  const body = (text: string) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    y = addWrappedText(doc, text, margin, y, contentW, lineH);
    y += 3;
  };
  const line = () => {
    doc.setDrawColor(180);
    doc.line(margin, y, pageW - margin, y);
    y += 5;
  };
  const newPage = () => {
    doc.addPage();
    y = margin;
  };

  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // Strips operator-identifying tokens from text for blind profiles
  const anonymize = (text: string): string => {
    if (!supplier) return text;
    const tokens = [supplier.name, supplier.keyContact ?? "", supplier.contactEmail ?? ""]
      .join(" ").split(/[\s,–—./]+/).filter(t => t.length > 3)
      .map(t => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
    let out = text;
    tokens.forEach(t => { out = out.replace(new RegExp(t, "gi"), "[Operator]"); });
    return out;
  };

  const supplierName = supplier?.name ?? "[SUPPLIER NAME]";
  const seekerName = seeker?.name ?? "[SEEKER NAME]";
  const region = supplier?.region ?? "[REGION]";
  const mw = supplier?.availableMW ?? 0;
  const cents = supplier?.estimatedAllInCents ?? 0;

  // ── Blind Teaser — anonymised pre-NCND profile ──────────────────────────
  if (template === "blind-teaser") {
    const assetRef = `ASSET-${String(supplier?.id ?? 0).padStart(4, "0")}`;
    const permitLabel = supplier?.permitStatus === "Confirmed"
      ? "Generation permits confirmed (documentation available post-NCND)"
      : supplier?.permitStatus === "Seller-stated"
      ? "Permits in place per seller — independent verification available under NCND"
      : "Permit status to be confirmed during diligence";
    const noQueue = supplier?.noInterconnectionQueue === true
      ? "No new grid interconnection queue required — existing infrastructure."
      : "Grid interconnection status: confirm in diligence.";
    const estMonths = supplier?.estimatedMonthsToEnergization;
    const timeline = estMonths
      ? `Est. ${estMonths}–${estMonths + 6} months to energization per seller (subject to diligence)`
      : "Energization timeline: confirm with seller during technical review";

    const typeHook = (() => {
      const t = (supplier?.type ?? "").toLowerCase();
      if (t.includes("btm")) return "Behind-the-meter gas generation — no grid exposure, load-scheduling flexibility, no interconnection queue.";
      if (t.includes("hydro")) return "Hydroelectric generation — renewable, low-carbon, high capacity factor, suitable for 24/7 CFE requirements.";
      if (t.includes("curtailment")) return "Curtailment-zone asset — negative pricing events eliminated with anchor industrial load; lowest ¢/kWh tier.";
      if (t.includes("solar")) return "Solar generation with existing grid connection — proven technology, predictable output, existing permits.";
      if (t.includes("nuclear")) return "Nuclear-adjacent power with 24/7 baseload profile — ideal for AI/HPC operations with high reliability requirements.";
      return "Existing operational infrastructure — not greenfield, not in interconnection queue.";
    })();

    h1(`BLIND ASSET PROFILE — ${assetRef}`);
    body(`Distributed by: PowerMatch Advisors | Reference Date: ${today}`);
    body("PRE-NCND DISTRIBUTION — Counterparty identity and exact location disclosed only after NCND execution.");
    line();
    h2("Asset Summary");
    body(`Asset Reference: ${assetRef} (name withheld — disclosed post-NCND)`);
    body(`General Region: ${region}`);
    body(`Asset Type: ${supplier?.type ?? "[TYPE]"}`);
    body(`Available Capacity: ${mw} MW`);
    body(`Indicative Pricing: Within current market range for ${supplier?.type ?? "this asset type"} in ${region.split(",")[0]} — specific ¢/kWh disclosed post-NCND`);
    body(noQueue);
    body(permitLabel);
    body(`Energization: ${timeline}`);
    line();
    h2("Why This Asset");
    body(typeHook);
    if (supplier?.keyPain) body(anonymize(supplier.keyPain));
    if (supplier?.signalNote) body(`Market signal: ${anonymize(supplier.signalNote)}`);
    line();
    h2("What You Receive After NCND");
    body("• Full operator identity and direct decision-maker contacts");
    body("• Exact asset location and site documentation");
    body("• Specific ¢/kWh pricing and contract structure");
    body("• Permit documentation and interconnection details");
    body("• Diligence package: financials, technical specs, legal status");
    line();
    h2("Next Steps");
    body("1. Execute NCND (2-page standard form — PowerMatch Advisors template or your own)");
    body("2. Receive full asset profile and operator introduction within 24 hours");
    body("3. Site visit / technical call within 5 business days of NCND execution");
    body("4. LOI / Exclusivity (90-day) if mutual interest confirmed");
    line();
    h2("Contact");
    body("PowerMatch Advisors");
    body("Alex Chen | alex@powermatch.io | +1 (212) 555-0190");
    body("Reply to this email or call directly — NCND can be executed same day.");
    newPage();
    h2("Important Notices");
    body("This blind profile is distributed on a strictly confidential basis for discussion purposes only. Recipient agrees to hold all information herein in confidence and not to circumvent PowerMatch Advisors in any transaction arising from this introduction.");
    body("All data presented is sourced from the asset operator and has not been independently verified by PowerMatch Advisors. Recipient must conduct its own due diligence. This document does not constitute legal, financial, or engineering advice.");
    body("PowerMatch Advisors earns a success-based brokerage fee per the executed MFPA. Fee is disclosed in full prior to any commitment.");
    doc.save(`blind-profile-${assetRef.toLowerCase()}.pdf`);
    return;
  }

  if (template === "site-teaser") {
    h1("SITE TEASER — CONFIDENTIAL");
    body(`Prepared by: PowerMatch Advisors | Date: ${today}`);
    body("NON-CIRCUMVENTION: Recipient agrees not to circumvent PowerMatch Advisors in any transaction arising from this introduction.");
    line();
    h2("Asset Summary");
    body(`Asset / Operator: ${supplierName}`);
    body(`General Vicinity: ${region} (Exact location disclosed post-NDA)`);
    body(`Available Capacity: ${mw} MW (expandable — contact for details)`);
    body(`Estimated All-In Price: ${cents}¢/kWh (subject to final diligence and contract)`);
    body(`Asset Type: ${supplier?.type ?? "[TYPE]"}`);
    body(`Voltage: 115–345 kV (site-specific; confirm in diligence)`);
    line();
    h2("Key Opportunity");
    body(supplier?.keyPain ?? "[SUPPLIER PAIN / OPPORTUNITY]");
    body(supplier?.notes ?? "[NOTES]");
    line();
    h2("Prospective Offtaker");
    body(`Entity: ${seekerName} (${seeker?.type ?? ""})`);
    body(`MW Required: ${seeker?.neededMW ?? 0} MW`);
    body(`Use Case: High-density compute (AI/HPC/Data Center)`);
    body(`Preferred Regions: ${seeker?.preferredRegions?.join(", ") ?? ""}`);
    const estMonths = supplier?.estimatedMonthsToEnergization;
    body(`Deployment Timeline: ${estMonths ? `Est. ${estMonths}–${estMonths + 6} months to energization per seller (subject to diligence)` : "Subject to diligence — confirm with seller during technical review"}`);
    line();
    h2("Indicative Deal Terms");
    body("Contract Type: Power Purchase Agreement (PPA) or Gas Supply + BTM Generation Agreement");
    body("Term: 7–15 years, with renewal options");
    body("Load Profile: Flexible/interruptible with demand response capability (adds grid value)");
    body(`Pricing Mechanism: Fixed or indexed; indicative all-in: ${cents > 0 ? `${cents}¢/kWh (subject to final diligence and negotiation)` : "to be confirmed during diligence"}`);
    body("Force Majeure / Curtailment: Standard provisions; flexible compute tolerates partial curtailment");
    line();
    h2("Next Steps");
    body("1. Execute NCND Agreement (template available)");
    body("2. PowerMatch provides full due diligence package (site data, permits, financials)");
    body("3. Site visit / technical call within 2 weeks");
    body("4. LOI / Exclusivity (90-day)");
    body("5. Full PPA negotiation and closing");
    newPage();
    h2("Disclaimer");
    body(DISCLAIMER);
    doc.save(`site-teaser-${supplierName.replace(/\s+/g, "-").toLowerCase()}.pdf`);
    return;
  }

  if (template === "loi") {
    h1("LETTER OF INTENT & EXCLUSIVITY AGREEMENT");
    body(`Date: ${today}`);
    body(`Between: ${supplierName} ("Power Provider") and ${seekerName} ("Offtaker")`);
    body(`Facilitated by: PowerMatch Advisors ("Broker")`);
    line();
    h2("1. Intent");
    body(`The parties hereby express their mutual intent to negotiate in good faith toward a Power Purchase Agreement for approximately ${mw} MW of power capacity in ${region}. Pricing shall be negotiated based on current market conditions; indicative range per seller: ${cents > 0 ? `${cents}–${(cents + 1).toFixed(1)}¢/kWh all-in` : "[to be confirmed in term sheet]"}.`);
    h2("2. Exclusivity Period");
    body("The Power Provider agrees to grant the Offtaker exclusive negotiating rights for a period of ninety (90) days from the date of this LOI ('Exclusivity Period'). During this period, Provider will not solicit, negotiate, or enter into competing agreements for the same capacity block without written consent of Offtaker.");
    h2("3. Good Faith Obligations");
    body("Both parties agree to: (a) provide requested due diligence materials within 10 business days; (b) respond to counterproposals within 5 business days; (c) engage qualified legal and technical advisors for final documentation.");
    h2("4. Non-Binding Nature");
    body("This LOI is non-binding except for Sections 2 (Exclusivity), 5 (Confidentiality), and 6 (Broker Fee). No binding obligation to execute a definitive agreement is created herein.");
    h2("5. Confidentiality");
    body("All information exchanged pursuant to this LOI is confidential and governed by a separate NCND Agreement executed concurrently.");
    h2("6. Broker Fee Acknowledgment");
    body("Both parties acknowledge that PowerMatch Advisors has facilitated this introduction and is entitled to a success-based brokerage fee per the Master Fee Protection Agreement (MFPA) executed separately.");
    h2("7. Governing Law");
    body("This LOI shall be governed by the laws of [State/Jurisdiction TBD] without regard to conflict of law provisions.");
    line();
    body("SIGNATURES:");
    body("Power Provider: _________________________ Date: _________");
    body("Offtaker: _________________________ Date: _________");
    body("Broker (PowerMatch): _________________________ Date: _________");
    newPage();
    body(DISCLAIMER);
    doc.save(`loi-${today.replace(/,?\s+/g, "-")}.pdf`);
    return;
  }

  if (template === "ncnd") {
    h1("NON-CIRCUMVENTION, NON-DISCLOSURE AGREEMENT (NCND)");
    body(`Date: ${today}`);
    body("Parties: PowerMatch Advisors ('Broker') and [Recipient Party Name] ('Recipient')");
    line();
    h2("1. Non-Disclosure");
    body("Recipient agrees to hold all Confidential Information (defined as: site location, operator identity, pricing, capacity details, counterparty identities, and deal terms) in strict confidence. Recipient will not disclose to any third party without prior written consent of Broker.");
    h2("2. Non-Circumvention");
    body("Recipient agrees not to circumvent, avoid, bypass, or obviate Broker's role in any transaction arising from introductions made by Broker. This includes direct contact with any party introduced by Broker for a period of twenty-four (24) months from date of introduction.");
    body("Circumvention includes but is not limited to: (a) direct negotiation with introduced parties; (b) use of affiliates or subsidiaries to bypass Broker; (c) structuring transactions to exclude Broker's fee.");
    h2("3. Permitted Disclosures");
    body("Recipient may disclose Confidential Information to: (a) employees with need-to-know; (b) legal/financial advisors bound by confidentiality; (c) as required by law (with prior notice to Broker where legally permissible).");
    h2("4. Term");
    body("This Agreement shall remain in effect for three (3) years from execution date.");
    h2("5. Remedies");
    body("Recipient acknowledges that breach of this Agreement would cause irreparable harm entitling Broker to injunctive relief in addition to monetary damages. Liquidated damages for circumvention: 150% of the brokerage fee that would have been earned.");
    h2("6. Governing Law");
    body("This Agreement is governed by the laws of [Jurisdiction TBD].");
    line();
    body("SIGNATURES:");
    body("Broker (PowerMatch Advisors): _________________________ Date: _________");
    body("Recipient: _________________________ Date: _________");
    body("Title: _________________________");
    newPage();
    body(DISCLAIMER);
    doc.save(`ncnd-agreement-${today.replace(/,?\s+/g, "-")}.pdf`);
    return;
  }

  if (template === "mfpa") {
    h1("MASTER FEE PROTECTION AGREEMENT (MFPA)");
    body(`Date: ${today}`);
    body("Between: PowerMatch Advisors ('Broker') and [Counterparty] ('Principal')");
    line();
    h2("1. Fee Structure");
    body("Broker shall earn a success-based brokerage fee upon closing of any transaction introduced by Broker, calculated as follows:");
    body("Option A — Per-MW Fee: $[X,000] per MW of contracted capacity (select: $5,000 / $10,000 / $15,000 per MW)");
    body("Option B — Residual Energy Fee: $[X] per MWh delivered during contract term (select: $0.50 / $1.00 / $1.50 per MWh)");
    body("Option C — Hybrid: $[X,000] per MW upfront + $[Y] per MWh residual (negotiated)");
    body("Note: Fee options and amounts are negotiable and must be agreed in writing prior to transaction closing.");
    h2("2. Payment Terms");
    body("Option A: 50% due within 10 days of PPA execution; 50% due within 10 days of commercial operation date (COD).");
    body("Option B/C residual: Monthly invoice based on metered delivery data, payable net-30.");
    h2("3. Fee Trigger Events");
    body("Brokerage fee is triggered by: (a) execution of a binding PPA or equivalent agreement; (b) execution of a gas supply agreement for BTM generation arrangements; (c) financial close of any project financed transaction involving introduced parties.");
    h2("4. Protected Introductions");
    body("All parties introduced by Broker are 'Protected Introductions' for 24 months. Any transaction between Principal and a Protected Introduction party triggers fee obligation regardless of Broker's direct involvement in closing.");
    h2("5. Exclusions");
    body("No fee is owed for: (a) transactions Principal can demonstrate were independently sourced prior to Broker's introduction; (b) transactions where Broker has provided written waiver.");
    h2("6. Dispute Resolution");
    body("Disputes resolved by binding arbitration under AAA Commercial Arbitration Rules in [Jurisdiction TBD]. Prevailing party entitled to reasonable attorneys' fees.");
    line();
    body("SIGNATURES:");
    body("Broker: _________________________ Date: _________");
    body("Principal: _________________________ Date: _________");
    newPage();
    body(DISCLAIMER);
    doc.save(`mfpa-${today.replace(/,?\s+/g, "-")}.pdf`);
    return;
  }

  if (template === "ppa-outline") {
    h1("POWER PURCHASE AGREEMENT — OUTLINE TERM SHEET");
    body(`Prepared: ${today} | Facilitated by: PowerMatch Advisors`);
    body(`Power Provider: ${supplierName} | Offtaker: ${seekerName}`);
    line();
    h2("1. Parties & Recitals");
    body(`Power Provider: ${supplierName}, a [Entity Type] organized under the laws of [Jurisdiction].`);
    body(`Offtaker: ${seekerName}, a [Entity Type] organized under the laws of [Jurisdiction].`);
    body("Purpose: Provider sells and delivers electrical energy; Offtaker purchases and takes delivery.");
    h2("2. Capacity & Delivery");
    body(`Contract Capacity: ${mw} MW (AC, net at delivery point)`);
    body("Delivery Point: [Substation / Meter Point ID — to be specified in Schedule A]");
    body("Voltage: [115 kV / 230 kV / 345 kV — site-specific]");
    body("Load Profile: Flexible/interruptible up to [X]% of hours; firm floor: [Y] MW");
    h2("3. Pricing");
    body(`Energy Price: ${cents}¢/kWh all-in (includes generation, transmission, ancillary where applicable)`);
    body("Price Adjustment: [Fixed / CPI-indexed at [X]% per year / Escalator TBD]");
    body("Curtailment Price: [Z]¢/kWh for curtailable hours (if applicable)");
    body("Metering: Revenue-grade ANSI C12.20 meters; readings monthly");
    h2("4. Term");
    body("Commencement: Commercial Operation Date (COD), estimated [Month Year]");
    body("Term: [7 / 10 / 15] years from COD");
    body("Renewal: [2 × 2-year renewal options at pricing TBD]");
    h2("5. Conditions Precedent");
    body("(a) Regulatory approvals (FERC, local utility, environmental permits)");
    body("(b) Financing close for any required infrastructure");
    body("(c) Technical interconnection study completion");
    body("(d) Insurance coverage per Schedule B");
    h2("6. Flexible Load Provisions");
    body("Offtaker may curtail load with [4-hour] advance notice, up to [15%] of annual energy.");
    body("Curtailment events provide demand response value shared per Schedule C.");
    body("Provider may request emergency curtailment with [2-hour] notice; Offtaker compensated at [D]¢/kWh.");
    h2("7. Force Majeure");
    body("Standard force majeure provisions apply. Includes: natural disaster, grid outage, regulatory action, war/conflict (relevant for Ethiopia/international sites).");
    h2("8. Representations & Warranties");
    body("Provider: Has authority to sell power; holds all required licenses; site is unencumbered.");
    body("Offtaker: Has authority to purchase; will maintain load commitments; has financing for infrastructure.");
    h2("9. Default & Termination");
    body("Payment default: 30-day cure period. Performance default: 60-day cure. Termination triggers: liquidated damages per Schedule D.");
    h2("10. Governing Law & Dispute Resolution");
    body("Governing Law: [Jurisdiction TBD — consider: Texas for US sites, Paraguay for ANDE, Ethiopian law for EEP]");
    body("Disputes: ICC Arbitration (for international), AAA Commercial Arbitration (for US).");
    line();
    h2("Schedules (to be attached)");
    body("A: Site description, metering details\nB: Insurance requirements\nC: Demand response / curtailment protocol\nD: Liquidated damages schedule\nE: Interconnection details");
    newPage();
    body(DISCLAIMER);
    doc.save(`ppa-outline-${supplierName.replace(/\s+/g, "-").toLowerCase()}.pdf`);
  }
}
